# Generated by Django 5.0.2 on 2024-02-28 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
