# Generated by Django 5.0.2 on 2024-02-28 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_material_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
